name: Build and Deploy Current Branches to linchpino-core-dev server

on:  
  pull_request:
      branches: [develop]
      types: [opened,reopened,synchronize]
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
      build-and-push-to-GHCR:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          - name: Build and push
            uses: docker/build-push-action@v3
            with:
              context: .
              file: Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              
      Deploy-to-linchpino-ui-server:
        runs-on: self-hosted
        permissions:
          contents: read
          packages: write
        needs: build-and-push-to-GHCR 
        steps:
          - name: Connect to linchpino-UI on GCP instance
            env:
              PR_NUMBER: ${{ github.event.number }}
            run: |
              cd /opt/linchpino-ui
              sudo git fetch --all
              sudo git reset --hard
              echo "the github ref is :" ${GITHUB_REF##*/}
              echo "currentBranch : " $currentBranch
              if [ ${GITHUB_REF##*/} == "merge" ]; then
              currentBranch=pr-$PR_NUMBER
              echo "Merage currentBranch :" $currentBranch
              sudo git checkout origin/develop --  docker-compose.yml
              echo "after git checkout"
              else
              currentBranch=${GITHUB_REF##*/}
              echo "currentBranch :" $currentBranch
              sudo git checkout origin/$currentBranch
              sudo git checkout origin/$currentBranch --  docker-compose.yml
              fi
              echo "yml"
              sudo sed -i "s/\/linchpino-ui:.*/\/linchpino-ui:$currentBranch/" docker-compose.yml
              docker-compose stop && docker-compose rm -f linchpino-ui && docker-compose pull linchpino-ui
              docker-compose up -d
